name: Odeal Performance Test Automation

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch: # Allows manual trigger

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Run JMeter performance test
      - name: Run JMeter Test
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk-headless
          curl -L https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.5.tgz -o jmeter.tgz
          tar -xzf jmeter.tgz
          ./apache-jmeter-5.5/bin/jmeter -n -t ./OdealWebsiteLoadTest.jmx -l ./results.jtl -e -o ./html-report

      # Upload HTML report as an artifact
      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: Performance-Test-Report
          path: ./html-report

      # Send the report via email
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Performance Test Report"
          body: "Find the attached performance test report."
          to: "recipient@example.com"
          from: ${{ secrets.EMAIL_USERNAME }}
          attachments: ./html-report/index.html
